image: fedora/latest
packages:
  - dotnet
  - wget
  - unzip
  - zip
tasks:
  - download-dalamud: |
      mkdir dalamud
      cd dalamud
      wget https://github.com/goatcorp/dalamud-distrib/raw/main/latest.zip
      unzip latest.zip
      rm latest.zip
  - build-plugin: |
      cd ChatTwo/ChatTwo
      dotnet build -c Release -p:IsCI=true
  - package: |
      cd ChatTwo/ChatTwo/bin/Release/net5.0-windows
      zip -r release.zip ChatTwo
artifacts:
  - ChatTwo/ChatTwo/bin/Release/net5.0-windows/ChatTwo/latest.zip
  - ChatTwo/ChatTwo/bin/Release/net5.0-windows/release.zip
